default:
  facebook_user: "cedeno97sc@gmail.com"
  facebook_pass: "Sebas.121297!"
  twitter_user: "cedeno_sc1297"
  twitter_pass: "Sebas.121297!"
  instagram_user: "cedeno_sc"
  instagram_pass: "Sebas.121297!"
  open_ai_api_key: "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"
